# Generated by Django 6.0.3 on 2026-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2; used for region and price display preferences.', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(blank=True, help_text='ISO 4217; how prices should be shown to this user.', max_length=3),
        ),
    ]
