# Generated by Django 6.0.3 on 2026-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_messages',
            field=models.BooleanField(default=True, help_text='Allow other users to send message requests.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private accounts hide posts and activity from non-owners.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_visibility',
            field=models.CharField(choices=[('public', 'Everyone'), ('only_me', 'Only me')], default='public', help_text="Who can see this user's posts.", max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_in_search',
            field=models.BooleanField(default=True, help_text='Appear in search results and user discovery.'),
        ),
    ]
