# Generated by Django 6.0.3 on 2026-06-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BusinessVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('national_id', 'National ID / passport'), ('business_registration', 'Business registration'), ('tourism_license', 'Tourism / hospitality license'), ('driver_license', "Driver's license"), ('vehicle_registration', 'Vehicle registration'), ('transport_insurance', 'Transport insurance'), ('operating_permit', 'Operating permit'), ('tour_guide_license', 'Tour guide license'), ('first_aid_cert', 'First aid certificate'), ('fire_safety_cert', 'Fire safety certificate'), ('food_handling_cert', 'Food handling certificate'), ('other', 'Other supporting document')], max_length=40)),
                ('file', models.FileField(upload_to='business_verification/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
