# Generated by Django 6.0.3 on 2026-06-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_platform_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformbookingnote',
            new_name='accounts_pl_booking_234c39_idx',
            old_name='accounts_pl_booking_0a8f2d_idx',
        ),
    ]
