# Generated by Django 6.0.3 on 2026-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_face_mode',
            field=models.BooleanField(default=False, help_text="No Face mode hides social surfaces (feeds, stories, other people's faces) and keeps only discovery/utility. Opt-in; default is the full social app."),
        ),
    ]
