# Generated by Django 6.0.3 on 2026-07-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_no_face_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('shop', 'Shop order'), ('accommodation', 'Stay'), ('guide', 'Guide'), ('vehicle', 'Vehicle rental'), ('bus_seat', 'Bus seat')], db_index=True, max_length=32)),
                ('record_id', models.PositiveIntegerField(db_index=True)),
                ('reason', models.CharField(choices=[('not_received', 'Not received / no-show'), ('not_as_described', 'Not as described'), ('damaged', 'Damaged / poor condition'), ('wrong_item', 'Wrong item / booking'), ('cancelled_by_seller', 'Seller cancelled'), ('other', 'Other')], default='other', max_length=40)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('refund_buyer', 'Refund buyer'), ('release_seller', 'Release to seller'), ('partial', 'Partial / other'), ('dismissed', 'Dismissed')], default='', max_length=32)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_disputes_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'record_id'], name='accounts_ma_source_9388a3_idx'), models.Index(fields=['status', '-created_at'], name='accounts_ma_status_b6411a_idx')],
            },
        ),
    ]
