# Generated by Django 6.0.3 on 2026-07-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_marketplace_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='community_impact',
            field=models.TextField(blank=True, help_text='What this business brings to the community / place.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='how_we_help',
            field=models.TextField(blank=True, help_text='How this business makes travel easier or more accessible.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='showcase_as_partner',
            field=models.BooleanField(default=False, help_text='Show this business as a travel partner hub (org-style page with deals & community).'),
        ),
        migrations.CreateModel(
            name='TravelOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('offer_kind', models.CharField(choices=[('eligibility', 'Eligibility rate'), ('discount', 'Discount'), ('package', 'Package / trip')], default='discount', max_length=20)),
                ('eligibility', models.CharField(choices=[('everyone', 'Everyone'), ('sadc', 'SADC residents'), ('student', 'Students'), ('local', 'Local / regional residents'), ('custom', 'Custom')], default='everyone', max_length=20)),
                ('eligibility_label', models.CharField(blank=True, help_text="Optional override, e.g. 'SADC passport holders'.", max_length=120)),
                ('price_label', models.CharField(blank=True, help_text="Human-readable deal, e.g. '50% off' or 'From N$1,200'.", max_length=80)),
                ('categories', models.JSONField(blank=True, default=list, help_text="Service categories this offer applies to, e.g. ['stays','food'].")),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_offers', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
