# Generated by Django 6.0.3 on 2026-06-28 15:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.TextField(blank=True, help_text='Cover image URL or uploaded path.')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('days', models.PositiveSmallIntegerField(default=1)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('transport_modes', models.JSONField(blank=True, default=list)),
                ('party', models.CharField(default='solo', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='NAD', max_length=8)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('draft', 'Draft')], db_index=True, default='public', max_length=16)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('moderation_reason', models.TextField(blank=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('stay', 'Accommodation'), ('food', 'Food & drink'), ('transport', 'Transport'), ('activity', 'Activities'), ('other', 'Other')], default='other', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='journeys.journey')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('place_name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(default='NA', max_length=8)),
                ('arrived_on', models.DateField()),
                ('left_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='journeys.journey')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('video', models.TextField(blank=True)),
                ('happened_at', models.DateField(blank=True, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journeys.journeystop')),
            ],
            options={
                'verbose_name_plural': 'journey entries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='journeys.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('journey', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JourneySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='journeys.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('journey', 'user')},
            },
        ),
    ]
