# Generated by Django 6.0.3 on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0002_journeyquestion_journeyanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="linked_listing_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="linked_listing_type",
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
