# Generated by Django 5.1.6 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0003_journey_featured_stop_listing_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="journey_stories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Author highlight channels for story rings",
            ),
        ),
    ]
