# Generated by Django 6.0.3 on 2026-07-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_journey_threaded_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='reflections',
            field=models.JSONField(blank=True, default=dict, help_text='Author reflections: {highs: [str], lows: [str], would_change: str, takeaway: str}.'),
        ),
        migrations.AddField(
            model_name='journey',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='journeyentry',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text="Ordered carousel media: [{kind: 'image'|'video', src, poster?}]."),
        ),
    ]
