# Generated by Django 6.0.3 on 2026-04-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodationlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodationbooking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accommodation.accommodationlisting'),
        ),
    ]
