# Generated by Django 6.0.3 on 2026-04-21 21:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationlisting',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text='Average guest rating 0–5', max_digits=3),
        ),
        migrations.AddField(
            model_name='accommodationlisting',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
