# Generated by Django 6.0.3 on 2026-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_listing_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationlisting',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('guesthouse', 'Guest house'), ('bed_and_breakfast', 'Bed & breakfast'), ('apartment', 'Apartment / flat'), ('lodge', 'Lodge'), ('hostel', 'Hostel'), ('villa', 'Villa / house'), ('resort', 'Resort'), ('camping_glamping', 'Camping / glamping'), ('other', 'Other')], db_index=True, default='guesthouse', max_length=32),
        ),
    ]
