# Generated by Django 6.0.3 on 2026-05-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0010_accommodationbooking_room_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationlisting',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='check_in_from',
            field=models.CharField(blank=True, default='14:00', help_text='Earliest check-in (24h), e.g. 14:00', max_length=12),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='check_out_until',
            field=models.CharField(blank=True, default='10:00', help_text='Latest check-out (24h), e.g. 10:00', max_length=12),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='FAQ: [{"question": "...", "answer": "..."}]'),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='guest_reviews',
            field=models.JSONField(blank=True, default=list, help_text='Reviews: [{"name": "...", "place": "...", "rating": 4.5, "body": "..."}]'),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='house_rules',
            field=models.TextField(blank=True, help_text='One rule per line is supported in the UI.'),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='media_gallery',
            field=models.JSONField(blank=True, default=list, help_text='Ordered gallery: [{"kind":"image"|"video","src":"path or URL"}]'),
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='room_types',
            field=models.JSONField(blank=True, default=list, help_text='Room/unit categories: name, optional description, max_guests, bedrooms, bed_summary, optional price_per_night, optional image URL.'),
        ),
        migrations.CreateModel(
            name='AccommodationListingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='accommodation.accommodationlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_listing_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('listing', 'user'), name='accommodation_listing_like_listing_user_uniq')],
            },
        ),
    ]
