# Generated by Django 6.0.3 on 2026-07-16 20:32

from decimal import Decimal
from django.db import migrations, models


def zero_out_unrated(apps, schema_editor):
    """Existing listings with no reviews carried the old 4.50 default — reset to 0."""
    Listing = apps.get_model('accommodation', 'AccommodationListing')
    Listing.objects.filter(rating_count=0).update(rating_avg=Decimal('0.00'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0016_remove_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationlisting',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average guest rating 0–5 (0 until the stay has reviews).', max_digits=3),
        ),
        migrations.RunPython(zero_out_unrated, noop),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='room_types',
            field=models.JSONField(blank=True, default=list, help_text="Room/unit categories. Each item supports: name (required), description, max_guests, bedrooms, bed_summary, price_per_night, compare_at_price (strike-through 'was' price for a sale), badge (short sale/special label), featured (bool), image (cover URL), images (gallery URLs)."),
        ),
    ]
