# Generated by Django 6.0.3 on 2026-07-16 08:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('category', models.CharField(choices=[('souvenirs', 'Souvenirs & gifts'), ('crafts', 'Handmade crafts'), ('jewellery', 'Jewellery'), ('clothing', 'Clothing & textiles'), ('art', 'Art & prints'), ('books_maps', 'Books & maps'), ('local_food', 'Local food & pantry'), ('gear', 'Safari & travel gear'), ('other', 'Other')], default='souvenirs', max_length=32)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('pickup_address', models.CharField(blank=True, help_text='Where travellers can collect — market stall, shop, lodge desk, etc.', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('price_note', models.CharField(blank=True, help_text='e.g. per item, from, per set', max_length=80)),
                ('in_stock', models.BooleanField(default=True)),
                ('pickup_available', models.BooleanField(default=True)),
                ('lodge_delivery', models.BooleanField(default=False, help_text='Can deliver to a lodge or hotel in the area.')),
                ('made_in_namibia', models.BooleanField(default=False)),
                ('artisan_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('cover_image', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
