# Generated by Django 6.0.3 on 2026-07-17 19:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopproduct_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('media', models.JSONField(blank=True, default=list, help_text='List of {"url": ..., "kind": "image"|"video"} the reviewer attached.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='Set when the reviewer purchased the product (verified purchase).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.shopproduct')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='product_review_rating_1_5'), models.UniqueConstraint(fields=('product', 'reviewer'), name='unique_product_review_per_user')],
            },
        ),
    ]
