# Generated by Django 6.0.3 on 2026-07-19 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopproduct_rating_avg_shopproduct_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_note',
            field=models.CharField(blank=True, help_text='Seller note for pickup window, courier, lodge drop, etc.', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('none', 'Not paid yet'), ('held', 'Held by Delve'), ('released', 'Released to seller'), ('refunded', 'Refunded to buyer')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Delve marketplace fee (from items only).', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount released to the seller after fee (includes shipping).', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid — awaiting seller'), ('ready', 'Ready for pickup / delivery'), ('shipped', 'Shipped'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
