# Generated by Django 6.0.3 on 2026-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public shop name. Falls back to the account display name when empty.', max_length=120),
        ),
    ]
