# Generated by Django 6.0.3 on 2026-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
