# Generated by Django 6.0.3 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shop_seller_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
    ]
