# Generated by Django 6.0.3 on 2026-07-21 15:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('category', models.CharField(choices=[('drives', 'Drives & scenic tours'), ('safari_wildlife', 'Safari & wildlife'), ('adventure', 'Adventure'), ('water', 'Water activities'), ('cultural', 'Cultural experiences'), ('wellness', 'Wellness & nature'), ('other', 'Other')], default='other', max_length=32)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('meeting_point', models.CharField(blank=True, max_length=300)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Typical duration in hours.', max_digits=5)),
                ('price_from', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Starting price per person (or group — see price_note).', max_digits=12)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('price_note', models.CharField(blank=True, help_text='e.g. per person, per group, from', max_length=80)),
                ('max_group_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('media_gallery', models.JSONField(blank=True, default=list, help_text='Ordered gallery: [{"kind":"image"|"video","src":"url","caption":""}]')),
                ('cover_image', models.TextField(blank=True, default='', help_text='Cover photo or video URL / storage path.')),
                ('cover_kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=16)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
