# Generated by Django 6.0.3 on 2026-07-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_reviews_and_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylisting',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='ActivityComment',
        ),
    ]
