# Generated by Django 6.0.3 on 2026-06-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotioncampaign',
            new_name='promotions__placeme_54d725_idx',
            old_name='promotions_p_placeme_idx',
        ),
        migrations.RenameIndex(
            model_name='promotioncampaign',
            new_name='promotions__target__aeec21_idx',
            old_name='promotions_p_target__idx',
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='placement',
            field=models.CharField(choices=[('homepage_stays', 'Homepage — Featured stays'), ('homepage_guides', 'Homepage — Featured guides'), ('homepage_food', 'Homepage — Featured food'), ('homepage_events', 'Homepage — Featured events'), ('homepage_transport', 'Homepage — Featured transport'), ('category_spotlight', 'Category list — Hero spotlight')], max_length=40),
        ),
    ]
