# Generated by Django 6.0.3 on 2026-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_rename_promotions_p_placeme_idx_promotions__placeme_54d725_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncampaign',
            name='placement',
            field=models.CharField(choices=[('homepage_stays', 'Homepage — Featured stays'), ('homepage_guides', 'Homepage — Featured guides'), ('homepage_food', 'Homepage — Featured food'), ('homepage_events', 'Homepage — Featured events'), ('homepage_transport', 'Homepage — Featured transport'), ('category_spotlight', 'Category list — Hero spotlight'), ('delvers_feed', 'Delvers feed — Sponsored injection'), ('community_feed', 'Community feed — Sponsored injection')], max_length=40),
        ),
    ]
