# Generated by Django 6.0.3 on 2026-06-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotioncampaign_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncampaign',
            name='provider_notes',
            field=models.TextField(blank=True, help_text='Message from provider when requesting.'),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16),
        ),
    ]
