# Generated by Django 6.0.3 on 2026-06-21 21:16

import django.db.models.deletion
from django.db import migrations, models


def seed_initial_promotion_products(apps, schema_editor):
    """Historical seed — must not import the live PromotionProduct model."""
    PromotionProduct = apps.get_model("promotions", "PromotionProduct")
    placements = {
        "homepage_stays": ("Stays", 250_000),
        "homepage_guides": ("Guides", 200_000),
        "homepage_food": ("Food", 180_000),
        "homepage_events": ("Events", 150_000),
        "delvers_feed": ("Delvers feed", 120_000),
    }
    regions = ["", "Khomas", "Erongo"]
    duration_days = 7
    for placement, (vertical, price_cents) in placements.items():
        for region in regions:
            slug_region = region.lower().replace(" ", "-") if region else "national"
            slug = f"{placement}_{duration_days}d_{slug_region}"
            region_label = region or "National"
            if placement == "delvers_feed":
                name = f"Sponsored {duration_days} days — Delvers feed — {region_label}"
            else:
                name = f"Homepage featured {duration_days} days — {vertical} — {region_label}"
            PromotionProduct.objects.get_or_create(
                slug=slug,
                defaults={
                    "name": name,
                    "placement": placement,
                    "region": region,
                    "duration_days": duration_days,
                    "price_cents": price_cents,
                    "currency": "NAD",
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_provider_promotion_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('placement', models.CharField(choices=[('homepage_stays', 'Homepage — Featured stays'), ('homepage_guides', 'Homepage — Featured guides'), ('homepage_food', 'Homepage — Featured food'), ('homepage_events', 'Homepage — Featured events'), ('homepage_transport', 'Homepage — Featured transport'), ('category_spotlight', 'Category list — Hero spotlight'), ('delvers_feed', 'Delvers feed — Sponsored injection'), ('community_feed', 'Community feed — Sponsored injection')], max_length=40)),
                ('region', models.CharField(blank=True, help_text='Blank = national reach.', max_length=120)),
                ('duration_days', models.PositiveSmallIntegerField(default=7)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='NAD', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'region', 'duration_days'],
            },
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='currency',
            field=models.CharField(blank=True, default='NAD', max_length=8),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='refund_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('requested', 'Requested'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='scheduled', max_length=16),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='promotions.promotionproduct'),
        ),
        migrations.RunPython(
            seed_initial_promotion_products,
            migrations.RunPython.noop,
        ),
    ]
