# Generated by Django 6.0.3 on 2026-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_products_and_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncampaign',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='listing_opens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
