# Generated by Django 6.0.3 on 2026-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_home_story_curator'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='homepin',
            new_name='promotions__placeme_379a6c_idx',
            old_name='promotions__placeme_home_pin_idx',
        ),
        migrations.RenameIndex(
            model_name='homestoryslide',
            new_name='promotions__channel_058838_idx',
            old_name='promotions__channel_7a1b2c_idx',
        ),
        migrations.AlterField(
            model_name='homepin',
            name='placement',
            field=models.CharField(choices=[('homepage_stays', 'Homepage — Featured stays'), ('homepage_guides', 'Homepage — Featured guides'), ('homepage_food', 'Homepage — Featured food'), ('homepage_events', 'Homepage — Featured events'), ('homepage_transport', 'Homepage — Featured transport'), ('category_spotlight', 'Category list — Hero spotlight'), ('delvers_feed', 'Delvers feed — Sponsored injection'), ('community_feed', 'Community feed — Sponsored injection')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='homepin',
            name='target_type',
            field=models.CharField(choices=[('accommodation', 'Stay listing'), ('guide', 'Guide profile'), ('food', 'Food venue'), ('event', 'Event'), ('vehicle', 'Vehicle rental'), ('bus_trip', 'Bus trip'), ('business', 'Business profile'), ('post', 'Delvers post')], max_length=32),
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='target_type',
            field=models.CharField(choices=[('accommodation', 'Stay listing'), ('guide', 'Guide profile'), ('food', 'Food venue'), ('event', 'Event'), ('vehicle', 'Vehicle rental'), ('bus_trip', 'Bus trip'), ('business', 'Business profile'), ('post', 'Delvers post')], max_length=32),
        ),
    ]
