# Generated by Django 6.0.3 on 2026-04-21 21:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideprofile',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.80'), help_text='Average client rating 0–5', max_digits=3),
        ),
        migrations.AddField(
            model_name='tourguideprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
