# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_add_rating_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourguideprofile",
            name="guest_reviews",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Reviews: [{"name": "...", "place": "...", "rating": 4.5, "body": "..."}]',
            ),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="response_hours_typical",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Typical first reply time in hours (for social proof).",
            ),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="tour_packages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Named tours: [{"id": "slug", "title": "...", "hours": 2, "price": "40.00"}]',
            ),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="years_guiding",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="licensed_guide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="languages_detail",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"language": "English", "level": "Fluent"}]',
            ),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="portfolio_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"src": "url", "caption": ""}]',
            ),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="default_meeting_point",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tourguideprofile",
            name="specialities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="guidebooking",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guidebooking",
            name="duration_hours",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="guidebooking",
            name="group_size",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="guidebooking",
            name="meeting_point",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guidebooking",
            name="package_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
