# Generated by Django 6.0.3 on 2026-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_profile_booking_enrichment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguideprofile',
            name='tour_packages',
            field=models.JSONField(blank=True, default=list, help_text='Named tours JSON: id,title,hours,price; optional keys: photo/image, description; gallery or photos/images (string URLs or [{"src"}]); reviews ([{name,place,rating,body}] same as guest_reviews).'),
        ),
    ]
