# Generated by Django 6.0.3 on 2026-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_alter_tourguideprofile_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideprofile',
            name='max_group_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Provider booking cap: max travellers per booking. Blank falls back to a default.', null=True),
        ),
    ]
