# Generated by Django 6.0.3 on 2026-07-19 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_tourguideprofile_max_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='payout_status',
            field=models.CharField(choices=[('none', 'Not paid yet'), ('held', 'Held by Delve'), ('released', 'Released to seller'), ('refunded', 'Refunded to buyer')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='guidebooking',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
