# Generated by Django 6.0.3 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0013_review_seller_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguideprofile',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2 primary country for this guide.', max_length=2),
        ),
    ]
