/** Shared environment key names — server secrets must never be prefixed with VITE_. */
export const SERVER_ENV_KEYS = [
  'NODE_ENV',
  'API_PORT',
  'DATABASE_URL',
  'SESSION_SECRET',
  'TRAVELER_WEB_URL',
  'ADMIN_WEB_URL',
  'ADMIN_WEB_ORIGIN',
  'ADMIN_SESSION_COOKIE_NAME',
  'ADMIN_CSRF_COOKIE_NAME',
  'ADMIN_SESSION_TTL_HOURS',
  'ADMIN_SESSION_IDLE_TIMEOUT_MINUTES',
  'DELVE_SERVICE',
  'BREVO_API_KEY',
  'BREVO_SENDER_EMAIL',
  'BREVO_SENDER_NAME',
  'EMAIL_VERIFICATION_TOKEN_TTL_HOURS',
  'EMAIL_VERIFICATION_RESEND_COOLDOWN_SECONDS',
  'EMAIL_VERIFICATION_MAX_SENDS_PER_HOUR',
  'S3_BUCKET',
  'S3_REGION',
  'S3_ENDPOINT',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'S3_PUBLIC_BASE_URL',
  'SESSION_LAST_SEEN_THROTTLE_SECONDS',
  'SESSION_RETENTION_DAYS',
  'SECURITY_EVENT_RETENTION_DAYS',
  'TRUST_GEO_HEADERS',
] as const

export const CLIENT_ENV_KEYS = ['VITE_API_BASE_URL'] as const

export type ServerEnvKey = (typeof SERVER_ENV_KEYS)[number]
export type ClientEnvKey = (typeof CLIENT_ENV_KEYS)[number]

export const DEFAULT_API_PORT = 4000
export const API_V2_PREFIX = '/api/v2'
