# Generated by Django 6.0.3 on 2026-05-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustrip',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Air conditioning", "Onboard toilet", "WiFi"]'),
        ),
        migrations.AddField(
            model_name='vehiclerentallisting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclerentallisting',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs or relative media paths'),
        ),
        migrations.AddField(
            model_name='vehiclerentallisting',
            name='included_features',
            field=models.JSONField(blank=True, default=list, help_text='List of short labels, e.g. ["Airport pickup", "Full insurance"]'),
        ),
        migrations.AddField(
            model_name='vehiclerentallisting',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Where the renter collects the vehicle', max_length=400),
        ),
    ]
