# Generated by Django 6.0.3 on 2026-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_vehicle_detail_and_bus_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Optional coach or route photo URL for listings.', max_length=500),
        ),
    ]
