# Generated by Django 6.0.3 on 2026-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_busroute_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of interior/route image URLs for trip detail gallery.'),
        ),
    ]
