# Generated by Django 6.0.3 on 2026-07-19 18:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_transport_provider_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatreservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='payout_status',
            field=models.CharField(choices=[('none', 'Not paid yet'), ('held', 'Held by Delve'), ('released', 'Released to seller'), ('refunded', 'Refunded to buyer')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vehiclerentalbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalbooking',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalbooking',
            name='payout_status',
            field=models.CharField(choices=[('none', 'Not paid yet'), ('held', 'Held by Delve'), ('released', 'Released to seller'), ('refunded', 'Refunded to buyer')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclerentalbooking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='vehiclerentalbooking',
            name='seller_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of interior/route media URLs or {"url","kind"} objects.'),
        ),
        migrations.AlterField(
            model_name='vehiclerentallisting',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of media URLs or {"url","kind"} objects (image/video)'),
        ),
    ]
