# Generated by Django 6.0.3 on 2026-07-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_review_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatreservationreview',
            name='seller_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatreservationreview',
            name='seller_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalreview',
            name='seller_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclerentalreview',
            name='seller_reply',
            field=models.TextField(blank=True),
        ),
    ]
