# Generated by Django 6.0.3 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_listing_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='busoperator',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
        migrations.AddField(
            model_name='vehiclerentallisting',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
    ]
