# Generated by Django 6.0.3 on 2026-04-04 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cuisine', models.CharField(choices=[('local', 'Local / Namibian'), ('grill', 'Grill & steak'), ('seafood', 'Seafood'), ('vegan', 'Vegan / vegetarian'), ('cafe', 'Café & bakery'), ('bar', 'Bar & nightlife'), ('international', 'International'), ('other', 'Other')], default='other', max_length=32)),
                ('region', models.CharField(max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('price_level', models.PositiveSmallIntegerField(default=2, help_text='1=budget, 4=fine dining')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
