# Generated by Django 6.0.3 on 2026-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodvenue',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='Extra amenity labels, e.g. ["Outdoor seating", "Card accepted"]'),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='closes_at',
            field=models.CharField(blank=True, help_text='Short label for list cards, e.g. 9 PM', max_length=40),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='dine_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='is_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='One line per day or range, e.g. Mon–Fri 08:00–17:00'),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='[{"id":1,"image":"url","caption":"","category":"food","is_cover":true}]'),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='popular_dish',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='reservations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='tagline',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='takeaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='venue_stories',
            field=models.JSONField(blank=True, default=list, help_text='Provider highlight channels for story rings'),
        ),
        migrations.AddField(
            model_name='foodvenue',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='foodvenue',
            name='cuisine',
            field=models.CharField(choices=[('local', 'Local / Namibian'), ('grill', 'Grill & steak'), ('seafood', 'Seafood'), ('cafe', 'Café'), ('bakery', 'Bakery'), ('pizza', 'Pizza'), ('asian', 'Asian'), ('fast_food', 'Fast food'), ('bar', 'Bar & nightlife'), ('vegan', 'Vegan / vegetarian'), ('international', 'International'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
