# Generated by Django 6.0.3 on 2026-07-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_venue_detail_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodvenue',
            name='guest_reviews',
            field=models.JSONField(blank=True, default=list, help_text='Host-seeded reviews: [{"name": "...", "place": "...", "rating": 4.5, "body": "..."}]'),
        ),
        migrations.CreateModel(
            name='FoodVenueReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_venue_reviews', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_reviews', to='food.foodvenue')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='food_venue_review_rating_1_5'), models.UniqueConstraint(fields=('venue', 'reviewer'), name='food_venue_review_one_per_user')],
            },
        ),
    ]
