# Generated by Django 6.0.3 on 2026-07-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodvenuereview',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='food.foodreservation'),
        ),
    ]
