# Generated by Django 6.0.3 on 2026-06-27 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_event_business_engagement'),
        ('events_app', '0006_phase3_social_growth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_ticket_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventRecurrenceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('business', 'Business'), ('food', 'Food & drink'), ('other', 'Other')], default='other', max_length=32)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/templates/')),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, help_text='Display price shown alongside external ticket link.', max_length=32)),
                ('ticket_url', models.URLField(blank=True, help_text='Required for paid recurring events — on-platform ticketing is not supported for templates.')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('default_start_time', models.TimeField(help_text='Local start time applied when spawning occurrences.')),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(default=5, help_text='0=Monday … 6=Sunday for weekly/biweekly schedules.')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1–28 for monthly schedules.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_spawned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_recurrence_templates', to='accounts.businessprofile')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_recurrence_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_events', to='events_app.eventrecurrencetemplate'),
        ),
    ]
