# Generated by Django 5.1.6 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0007_phase4_monetization"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_stories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Organizer highlight channels for story rings",
            ),
        ),
    ]
