# Generated by Django 6.0.3 on 2026-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0013_event_cover_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
        migrations.AddField(
            model_name='eventrecurrencetemplate',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ISO 3166-1 alpha-2, e.g. NA, ZA, KE.', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('business', 'Business'), ('food', 'Foodies'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional hero gallery media (cover is separate).'),
        ),
        migrations.AlterField(
            model_name='eventcategoryfollow',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('business', 'Business'), ('food', 'Foodies'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='eventrecurrencetemplate',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('business', 'Business'), ('food', 'Foodies'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
