# Generated by Django 6.0.3 on 2026-07-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TossLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('viewpoint', 'Viewpoint'), ('hike', 'Hike / trail'), ('beach', 'Beach / coast'), ('market', 'Market'), ('cafe', 'Café / spot to linger'), ('culture', 'Culture / heritage'), ('wildlife', 'Wildlife'), ('hidden', 'Hidden gem'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('open_source_ref', models.CharField(blank=True, help_text='OpenStreetMap node/way id, Wikidata Q-id, or similar organic reference.', max_length=300)),
                ('is_excluded', models.BooleanField(default=False, help_text='Kill switch: set when commercial flags reach the threshold.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='coin_toss_t_latitud_afb4a0_idx'), models.Index(fields=['is_excluded'], name='coin_toss_t_is_excl_60ac08_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('voter_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_toss_votes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='coin_toss.tosslocation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'location'), name='uniq_coin_toss_vote_user_location')],
            },
        ),
        migrations.CreateModel(
            name='AntiCommercialFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_toss_flags', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_flags', to='coin_toss.tosslocation')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'location'), name='uniq_coin_toss_flag_user_location')],
            },
        ),
    ]
