# Generated by Django 6.0.3 on 2026-07-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_toss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tosslocation',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text='Photos/videos: [{"url": "...", "kind": "image"|"video"}].'),
        ),
        migrations.AlterField(
            model_name='tosslocation',
            name='category',
            field=models.CharField(choices=[('viewpoint', 'Viewpoint'), ('hike', 'Hike / trail'), ('beach', 'Beach / coast'), ('water', 'Water / swim'), ('market', 'Market'), ('cafe', 'Café / spot to linger'), ('culture', 'Culture / heritage'), ('wildlife', 'Wildlife'), ('sports', 'Sports / active'), ('event', 'Event / happening'), ('free', 'Free to visit'), ('hidden', 'Hidden gem'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
