# Generated by Django 6.0.3 on 2026-07-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_secret', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires payment method'), ('requires_confirmation', 'Requires confirmation'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='requires_payment_method', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='nad', max_length=8)),
                ('target_type', models.CharField(choices=[('shop_order', 'Shop order'), ('accommodation', 'Stay booking'), ('guide', 'Guide booking'), ('vehicle', 'Vehicle booking'), ('bus_seat', 'Bus seat'), ('bus_seat_bulk', 'Bus seats (bulk)')], db_index=True, max_length=32)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('brand', models.CharField(blank=True, default='visa', max_length=32)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('charge_id', models.CharField(blank=True, max_length=64)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulated_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
