# Generated by Django 6.0.3 on 2026-07-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('blocked_reason', models.TextField(blank=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('community', 'Community'), ('delvers', 'Delvers'), ('journeys', 'Journeys'), ('events', 'Events'), ('food', 'Food'), ('stays', 'Stays')], db_index=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tags.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'tag'], name='tags_tagged_scope_8a0277_idx'), models.Index(fields=['content_type', 'object_id'], name='tags_tagged_content_eaa81e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tag', 'content_type', 'object_id'), name='tags_taggeditem_unique_tag_object')],
            },
        ),
    ]
