# Generated by Django 6.0.3 on 2026-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='scope',
            field=models.CharField(choices=[('community', 'Community'), ('groups', 'Groups'), ('delvers', 'Delvers'), ('journeys', 'Journeys'), ('events', 'Events'), ('food', 'Food'), ('stays', 'Stays')], db_index=True, max_length=32),
        ),
    ]
