# Step 4: Create Delve Heroku apps and set config vars.
# Prerequisites: Heroku CLI installed and `heroku login` completed.
#
# Usage (from repo root, in your own terminal — login needs a browser):
#   heroku login
#   .\scripts\heroku-create-apps.ps1
# Optional overrides:
#   .\scripts\heroku-create-apps.ps1 -ApiApp delve-api -AppApp delve-app -AdminApp delve-admin

param(
    [string]$ApiApp = "delve-api",
    [string]$AppApp = "delve-app",
    [string]$AdminApp = "delve-admin"
)

$ErrorActionPreference = "Stop"

# Prefer npm-global CLI if present (common on Windows).
$npmHeroku = Join-Path $env:APPDATA "npm"
if (Test-Path (Join-Path $npmHeroku "heroku.cmd")) {
    $env:Path = "$npmHeroku;" + $env:Path
}

function Require-Heroku {
    $cmd = Get-Command heroku -ErrorAction SilentlyContinue
    if (-not $cmd) {
        throw "Heroku CLI not found. Run: npm install -g heroku   then: heroku login"
    }
    $who = & heroku auth:whoami 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Not logged in. In your terminal run: heroku login"
    }
    Write-Host "Logged in as $who"
}

function New-AppSuffix {
    -join ((48..57 + 97..122) | Get-Random -Count 6 | ForEach-Object { [char]$_ })
}

function Ensure-App([string]$Name, [string]$Buildpack) {
    heroku apps:info -a $Name 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "App already exists: $Name"
        heroku buildpacks:set $Buildpack -a $Name | Out-Null
        return $Name
    }

    Write-Host "Creating app: $Name"
    heroku create $Name 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        $Name = "$Name-$(New-AppSuffix)"
        Write-Host "Name taken; creating $Name"
        heroku create $Name
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to create app $Name"
        }
    }

    heroku buildpacks:set $Buildpack -a $Name | Out-Null
    return $Name
}

function App-WebUrl([string]$Name) {
    return "https://$Name.herokuapp.com"
}

Require-Heroku

Write-Host "`n=== Creating apps ==="
$ApiApp = Ensure-App $ApiApp "heroku/python"
$AppApp = Ensure-App $AppApp "heroku/nodejs"
$AdminApp = Ensure-App $AdminApp "heroku/nodejs"

$apiUrl = App-WebUrl $ApiApp
$appUrl = App-WebUrl $AppApp
$adminUrl = App-WebUrl $AdminApp

Write-Host "`n=== Postgres (API) ==="
$addons = heroku addons -a $ApiApp 2>&1 | Out-String
if ($addons -match "heroku-postgresql") {
    Write-Host "Postgres already attached to $ApiApp"
}
else {
    $plans = @("heroku-postgresql:essential-0", "heroku-postgresql:mini", "heroku-postgresql:basic")
    $created = $false
    foreach ($plan in $plans) {
        Write-Host "Trying $plan ..."
        heroku addons:create $plan -a $ApiApp
        if ($LASTEXITCODE -eq 0) {
            $created = $true
            break
        }
    }
    if (-not $created) {
        throw "Could not attach Postgres. Add a payment method at https://dashboard.heroku.com/account/billing then re-run."
    }
}

# Cryptographically random secret
$bytes = New-Object byte[] 48
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$secret = [Convert]::ToBase64String($bytes) -replace "[+/=]", ""

Write-Host "`n=== API config vars ==="
heroku config:set -a $ApiApp `
    DJANGO_SECRET_KEY="$secret" `
    DJANGO_DEBUG="false" `
    DJANGO_ALLOWED_HOSTS="$ApiApp.herokuapp.com" `
    CORS_ALLOWED_ORIGINS="$appUrl,$adminUrl" `
    CSRF_TRUSTED_ORIGINS="$appUrl,$adminUrl" `
    FRONTEND_URL="$appUrl" `
    EMAIL_BACKEND="django.core.mail.backends.console.EmailBackend" `
    DEFAULT_FROM_EMAIL="noreply@$ApiApp.herokuapp.com"
if ($LASTEXITCODE -ne 0) { throw "Failed to set API config vars" }

Write-Host "`n=== Traveller app config vars (Vite build-time) ==="
heroku config:set -a $AppApp `
    VITE_USE_MOCKS="false" `
    VITE_API_URL="$apiUrl" `
    VITE_ADMIN_APP_URL="$adminUrl"
if ($LASTEXITCODE -ne 0) { throw "Failed to set traveller config vars" }

Write-Host "`n=== Admin app config vars (Vite build-time) ==="
heroku config:set -a $AdminApp `
    VITE_USE_MOCKS="false" `
    VITE_API_URL="$apiUrl" `
    VITE_PUBLIC_APP_URL="$appUrl"
if ($LASTEXITCODE -ne 0) { throw "Failed to set admin config vars" }

# Git remotes (from repo root)
$root = Split-Path -Parent $PSScriptRoot
Push-Location $root
try {
    heroku git:remote -a $ApiApp -r heroku-api 2>$null
    heroku git:remote -a $AppApp -r heroku-app 2>$null
    heroku git:remote -a $AdminApp -r heroku-admin 2>$null
}
finally {
    Pop-Location
}

# Persist names for later deploy steps
$outFile = Join-Path $PSScriptRoot "heroku-apps.env"
@"
# Generated by heroku-create-apps.ps1 — do not commit secrets (none stored here).
HEROKU_API_APP=$ApiApp
HEROKU_APP_APP=$AppApp
HEROKU_ADMIN_APP=$AdminApp
HEROKU_API_URL=$apiUrl
HEROKU_APP_URL=$appUrl
HEROKU_ADMIN_URL=$adminUrl
"@ | Set-Content -Path $outFile -Encoding utf8

Write-Host @"

=== Step 4 complete ===

API:     $apiUrl
App:     $appUrl
Admin:   $adminUrl

Saved:   scripts\heroku-apps.env
Git remotes: heroku-api, heroku-app, heroku-admin

EMAIL is console-only for now (safe default). After you have SMTP credentials:

  heroku config:set -a $ApiApp ``
    EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend" ``
    DEFAULT_FROM_EMAIL="Delve <your-verified-sender@email.com>" ``
    EMAIL_HOST="smtp-relay.brevo.com" ``
    EMAIL_PORT="587" ``
    EMAIL_USE_TLS="true" ``
    EMAIL_HOST_USER="your-login@email.com" ``
    EMAIL_HOST_PASSWORD="your-smtp-key"

Optional media (Cloudinary):

  heroku config:set -a $ApiApp CLOUDINARY_URL="cloudinary://api_key:api_secret@cloud_name"

Next — deploy (from repo root, after committing Step 1–3):

  git subtree push --prefix=backend heroku-api main
  git subtree push --prefix=frontend heroku-app main
  git subtree push --prefix="Delve Admin" heroku-admin main

Then:

  heroku run -a $ApiApp python manage.py createsuperuser
  heroku run -a $ApiApp python manage.py send_test_email you@example.com

"@
