# Generated by Django 6.0.3 on 2026-04-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Short video (e.g. mp4, webm). Use image or video, not both.', null=True, upload_to='posts/videos/'),
        ),
    ]
