# Generated by Django 6.0.3 on 2026-06-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_phase3_social_growth'),
        ('social', '0004_content_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional link to an event for Delvers moments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delvers_posts', to='events_app.event'),
        ),
    ]
