# Generated by Django 6.0.3 on 2026-07-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_venue_detail_fields'),
        ('social', '0008_post_transport_place_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_venue',
            field=models.ForeignKey(blank=True, help_text='Optional link to a food venue for Delvers moments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delvers_posts', to='food.foodvenue'),
        ),
    ]
