# Generated by Django 6.0.3 on 2026-07-07 20:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_comment_threads_dislike_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Short video (e.g. mp4, webm). Use image or video, not both.', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='posts/videos/'),
        ),
    ]
