# Generated by Django 6.0.3 on 2026-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_tagfollow_index_names_and_highlight_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_trim_end',
            field=models.FloatField(blank=True, help_text='Trim end (seconds). Applied on delivery for Cloudinary sources.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_trim_start',
            field=models.FloatField(blank=True, help_text='Trim start (seconds). Applied on delivery for Cloudinary sources.', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_trim_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_trim_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
