# Generated by Django 6.0.3 on 2026-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_groups/messages/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_groups/messages/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
