# Generated by Django 6.0.3 on 2026-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_groupmessage_delete_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='community_groups/messages/'),
        ),
    ]
