# Generated by Django 6.0.3 on 2026-07-07 20:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_rich_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='community_groups/messages/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='community_groups/messages/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='community_groups/messages/'),
        ),
    ]
